"""Define cases to investigate"""
SEED = 10

MODEL_HORIZON = 52

SHOCK_INDEX = 10

PERMIT_PRICE = 40

FORECAST_INTERVALS_MPC = 6

FORECAST_INTERVALS_REVENUE_REBALANCE = 1

FORECAST_UNCERTAINTY_INCREMENT = 0.05

INITIAL_ROLLING_SCHEME_REVENUE = 0

START_REVENUE_RAMP_INDEX = 10

REVENUE_RAMP_INTERVALS = 10

REVENUE_RAMP_INCREMENT = 3e6

benchmark_cases = [
    {'description': 'business as usual - no shocks',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'NO_SHOCKS',
     # 'forecast_shock': False,
     # 'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'NO_UPDATE',
     'default_baseline': 0,
     'initial_permit_price': 0,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     # 'forecast_intervals': 2,
     # 'forecast_uncertainty_increment': 0.05,
     # 'revenue_target': 'neutral',
     # 'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },

    {'description': 'business as usual - emissions intensity shock',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'EMISSIONS_INTENSITY_SHOCK',
     # 'forecast_shock': False,
     'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'NO_UPDATE',
     'default_baseline': 0,
     'initial_permit_price': 0,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     # 'forecast_intervals': 2,
     # 'forecast_uncertainty_increment': 0.05,
     # 'revenue_target': 'neutral',
     # 'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },

    {'description': 'carbon tax - no shocks',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'NO_SHOCKS',
     # 'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'NO_UPDATE',
     'default_baseline': 0,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     # 'forecast_intervals': 2,
     # 'forecast_uncertainty_increment': 0.05,
     # 'revenue_target': 'neutral',
     # 'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },

    {'description': 'carbon tax - emissions intensity shock',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'EMISSIONS_INTENSITY_SHOCK',
     # 'forecast_shock': False,
     'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'NO_UPDATE',
     'default_baseline': 0,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     # 'forecast_intervals': 2,
     # 'forecast_uncertainty_increment': 0.05,
     # 'revenue_target': 'neutral',
     # 'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },
]


updating_cases = [
    {'description': 'revenue rebalance update - revenue neutral target - no shocks - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'NO_SHOCKS',
     # 'forecast_shock': False,
     # 'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'REVENUE_REBALANCE_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_REVENUE_REBALANCE,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'neutral',
     'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },

    {'description': 'revenue rebalance update - revenue neutral target - emissions intensity shock - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'EMISSIONS_INTENSITY_SHOCK',
     # 'forecast_shock': False,
     'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'REVENUE_REBALANCE_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_REVENUE_REBALANCE,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'neutral',
     'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },

    {'description': 'mpc update - revenue neutral target - no shocks - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'NO_SHOCKS',
     # 'forecast_shock': False,
     # 'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'MPC_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_MPC,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'neutral',
     'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },

    {'description': 'mpc update - revenue neutral target - emissions intensity shock - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'EMISSIONS_INTENSITY_SHOCK',
     # 'forecast_shock': False,
     'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'MPC_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_MPC,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'neutral',
     'renewables_eligibility': 'ineligible',
     # 'revenue_ramp_calibration_interval_start': 1,
     # 'revenue_ramp_intervals': 10,
     # 'revenue_ramp_increment': 1e6
     },

    {'description': 'revenue rebalance update - revenue ramp up target - no shocks - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'NO_SHOCKS',
     # 'forecast_shock': False,
     # 'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'REVENUE_REBALANCE_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_REVENUE_REBALANCE,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'ramp_up',
     'renewables_eligibility': 'ineligible',
     'revenue_ramp_calibration_interval_start': START_REVENUE_RAMP_INDEX,
     'revenue_ramp_intervals': REVENUE_RAMP_INTERVALS,
     'revenue_ramp_increment': REVENUE_RAMP_INCREMENT,
     },

    {'description': 'mpc update - revenue ramp up target - no shocks - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'NO_SHOCKS',
     # 'forecast_shock': False,
     # 'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'MPC_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_MPC,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'ramp_up',
     'renewables_eligibility': 'ineligible',
     'revenue_ramp_calibration_interval_start': START_REVENUE_RAMP_INDEX,
     'revenue_ramp_intervals': REVENUE_RAMP_INTERVALS,
     'revenue_ramp_increment': REVENUE_RAMP_INCREMENT,
     },

    {'description': 'revenue rebalance update - revenue neutral target - emissions intensity shock unanticipated - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'EMISSIONS_INTENSITY_SHOCK',
     'forecast_shock': True,
     'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'REVENUE_REBALANCE_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_REVENUE_REBALANCE,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'ramp_up',
     'renewables_eligibility': 'ineligible',
     'revenue_ramp_calibration_interval_start': START_REVENUE_RAMP_INDEX,
     'revenue_ramp_intervals': REVENUE_RAMP_INTERVALS,
     'revenue_ramp_increment': REVENUE_RAMP_INCREMENT,
     },

    {'description': 'mpc update - revenue neutral target - emissions intensity shock unanticipated - renewables ineligible',
     'model_horizon': MODEL_HORIZON,
     'shock_option': 'EMISSIONS_INTENSITY_SHOCK',
     'forecast_shock': True,
     'shock_index': SHOCK_INDEX,
     'seed': SEED,
     'update_mode': 'MPC_UPDATE',
     'default_baseline': 1.02,
     'initial_permit_price': PERMIT_PRICE,
     'initial_rolling_scheme_revenue': INITIAL_ROLLING_SCHEME_REVENUE,
     'forecast_intervals': FORECAST_INTERVALS_MPC,
     'forecast_uncertainty_increment': FORECAST_UNCERTAINTY_INCREMENT,
     'revenue_target': 'ramp_up',
     'renewables_eligibility': 'ineligible',
     'revenue_ramp_calibration_interval_start': START_REVENUE_RAMP_INDEX,
     'revenue_ramp_intervals': REVENUE_RAMP_INTERVALS,
     'revenue_ramp_increment': REVENUE_RAMP_INCREMENT,
     },

]
